[project]
name = "nlp-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyaudio>=0.2.14",
    "speechrecognition>=3.14.4",
]
