[project]
name = "nlp-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "piper-tts>=1.3.0",
    "pyaudio>=0.2.14",
    "soundfile>=0.13.1",
    "speechrecognition>=3.14.4",
]
